# NOTE: 一応サンプルなので複数構成をひとつに詰め込んでいる。

name: Deploy client

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: echo "CLIENT_BASE_PATH=/$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
      - uses: actions/cache@v2
        id: client-npm-cache
        with:
          path: "node_modules"
          key: client-npm-${{ hashFiles('package-lock.json') }}
      - uses: actions/cache@v2
        id: server-npm-cache
        with:
          path: "server/node_modules"
          key: server-npm-${{ hashFiles('server/package-lock.json') }}
      - run: npm install
        if: steps.client-npm-cache.outputs.cache-hit != 'true'
      - run: npm install --prefix server
        if: steps.server-npm-cache.outputs.cache-hit != 'true'
      - run: npm run build:client
        env:
          API_ORIGIN: ${{ secrets.API_ORIGIN }}
          BASE_PATH: ${{ secrets.API_BASE_PATH }}
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
      - uses: google-github-actions/upload-cloud-storage@main
        with:
          path: ./out
          destination: ${{ secrets.GCP_STORAGE_BUCKET }}
